export const REGISTER = "REGISTER";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const USER_PREFERENCE = "USER_PREFERENCE";
export const USER_PREFERENCE_SUCCESS = "USER_PREFERENCE_SUCCESS";
export const USER_PREFERENCE_FAILURE = "USER_PREFERENCE_FAILURE";

export const USER_PREFERENCE_SAVE = "USER_PREFERENCE_SAVE";
export const USER_PREFERENCE_SAVE_SUCCESS = "USER_PREFERENCE_SAVE_SUCCESS";
export const USER_PREFERENCE_SAVE_FAILURE = "USER_PREFERENCE_SAVE_FAILURE";

export const LOGOUT = "LOGOUT";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";


