export const GET_NEWS_API_ARTICLES = "GET_NEWS_API_ARTICLES";
export const GET_NEWS_API_ARTICLES_SUCCESS = "GET_NEWS_API_ARTICLES_SUCCESS";
export const GET_NEWS_API_ARTICLES_FAILURE = "GET_NEWS_API_ARTICLES_FAILURE";